AUT-271: make separate tags and docker images pushes for production deploys of autograph-edge
mozilla-services/autograph-edge pull request #333
Opened 2024-10-11 20:47 UTC by bhearsum

This change gives us separate tags for prereleases and releases, which will allow our deployment pipeline to separate out stage & production deploys.

I've also adjusted the `latest` tag to only be used on pushes to main, rather than all deployments. This will ensure that any ongoing dev work against main won't be disrupted if we cut a release.

Here's some example runs in my own repo (they fail, but the important part is the metadata step):
* [A push to main](https://github.com/bhearsum/autograph-edge/actions/runs/11298955041/job/31428961407), which just generates a `latest` tag
* [Publishing the `1.1.1` prerelease](https://github.com/bhearsum/autograph-edge/actions/runs/11298968687/job/31428998722) just generates a `1.1.1-prerelease` tag
* [Republishing `1.1.1` as a full release](https://github.com/bhearsum/autograph-edge/actions/runs/11298988470/job/31429054717) just generates a `1.1.1` tag

2024-10-28 16:01 UTC, jmhodges requested changes
Same changes requested as from the deploy doc (tag, don't build for stage and prod) and use the stage & prod names

2024-10-28 16:30 UTC, bhearsum commented
> Same changes requested as from the deploy doc (tag, don't build a second or third time for stage and prod) and use the stage & prod names

Coming soon! Currently testing some things in my own repo.

2024-10-28 19:32 UTC, jmhodges commented
Yeah, that was just me clearing out my review queue so I stop getting alerts!

2024-10-31 23:32 UTC, jmhodges requested changes
(Just clearing this so my Slack alerts stop firing on it)

crane work has to happen here!

2024-11-01 00:00 UTC, bhearsum commented
Oops, I thought I pushed that already :laughing:

2024-11-01 00:00 UTC, jmhodges approved these changes

2024-11-01 00:24 UTC, merged